### ISSUE TITLE
Add a web framework

### ISSUE THREAD

**Issue by ghost** [fallprogrammer4/GlobalHumanWealth-app#3]
So, I'm done for the semester now, and was thinking of adding a web framework now that we have the basic functionality down. A quick web search brought me to Flask:

[https://www.digitalocean.com/community/tutorials/how-to-make-a-web-application-using-flask-in-python-3](https://www.digitalocean.com/community/tutorials/how-to-make-a-web-application-using-flask-in-python-3)

However, since flask just serves a webpage and does not provide facilities for backend scripts and databases, I was thinking of writing the website using Django, then deploying onto an Apache server:

[https://docs.djangoproject.com/en/5.0/intro/tutorial01/](https://docs.djangoproject.com/en/5.0/intro/tutorial01/)
[https://www.thecodeship.com/deployment/deploy-django-apache-virtualenv-and-mod_wsgi/](https://www.thecodeship.com/deployment/deploy-django-apache-virtualenv-and-mod_wsgi/)

What are your thoughts?

**Comment by fallprogrammer4** [comment]
That is a great call you made! I will look more into it, analyze, plan, and get right back to you.
